### ISSUE TITLE
Azure Invitation

### ISSUE THREAD

**Issue by IanMcCrabb** [HughCraig/TLCMap#10]
Hi Bill, I've not received any invitation from Azure.  I have an Azure acocunt under ianmccrabb@systemiksolutions.com

**Comment by BillPascoe** [comment]
It's showing you in the role list as owner, so try this link and see if you see a view of all the TLCMap stuff, or if it blocks you:
https://portal.azure.com/85542c9f-eaa7-4e74-89b5-aadeb181fe60
(Assuming also you checked the spam folder for the invite???)

**Comment by IanMcCrabb** [comment]
Thanks Bill,  all good
