### ISSUE TITLE
Main Search Fuzzy Fail and anpsid not validating.

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/TLCMap#102]
Search for "Darwin" and choose 'Fuzzy' and it gives SQL error:
SQLSTATE[42883]: Undefined function: 7 ERROR: operator does not exist: text % unknown 

If I search for 'Darwin' and choose 'anpsid' it gives me the following error. It is expecting numeric not text input, so should just validate and fail with a nice error message, such as 'ANPS ID should be a number'.
SQLSTATE[22P02]: Invalid text representation: 7 ERROR: invalid input syntax for type bigint

**Comment by yangli0516** [comment]
The first error is caused by the pg_trgm module is not enabled on the testing database. Have enabled the module, and the error is gone.

**Comment by yangli0516** [comment]
For the second issue, the frontend validation has been added. Though I think backend validation should be in place also. This might be another issue as I don't see any backend validation in the current code.
