### ISSUE TITLE
Shape search errors

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/TLCMap#103]
Drawing a square works ok, eg:
15765 results for this search:
https://test.tlcmap.org/ghap/search?searchausgaz=on&searchpublicdatasets=on&_token=BK95dRa0nOKBgUFxPbm15GJBuftFFvRWydhQBYiz&bbox=150.733362%2C-34.522218%2C151.96391%2C-33.648522

But draw a circle and search gives SQL error:
SQLSTATE[42883]: Undefined function: 7 ERROR: function st_point(numeric, numeric) does not exist LINE 1

Draw a polygon gives SQL error:
ERROR: function st_geomfromtext(unknown) does not exist LINE 1: ..."dataset"."id" and "public" = $1) and ST_CONTAINS(ST_GEOMFRO... ^ HINT: No function matches the given name and argument types.

Under advanced search 'Search within a KML Polygon' gives error
SQLSTATE[42883]: Undefined function: 7 ERROR: function st_geomfromtext(unknown) does not exist LINE 1: ...ate from "gazetteer"."register" where ST_CONTAINS(ST_GEOMFRO... ^ HINT: No function matches the given name and argument types.

**Comment by BillPascoe** [comment]
If you want a polygon kml file to test the upload option, paste this into a text file and save as 'testpolygon.kml':

<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2" xmlns:gx="http://www.google.com/kml/ext/2.2" xmlns:kml="http://www.opengis.net/kml/2.2" xmlns:atom="http://www.w3.org/2005/Atom">
<Document>
	<name>testpolygon.kml</name>
	<Style id="s_ylw-pushpin">
		<IconStyle>
			<scale>1.1</scale>
			<Icon>
				<href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>
			</Icon>
			<hotSpot x="20" y="2" xunits="pixels" yunits="pixels"/>
		</IconStyle>
	</Style>
	<Style id="s_ylw-pushpin_hl">
		<IconStyle>
			<scale>1.3</scale>
			<Icon>
				<href>http://maps.google.com/mapfiles/kml/pushpin/ylw-pushpin.png</href>
			</Icon>
			<hotSpot x="20" y="2" xunits="pixels" yunits="pixels"/>
		</IconStyle>
	</Style>
	<StyleMap id="m_ylw-pushpin">
		<Pair>
			<key>normal</key>
			<styleUrl>#s_ylw-pushpin</styleUrl>
		</Pair>
		<Pair>
			<key>highlight</key>
			<styleUrl>#s_ylw-pushpin_hl</styleUrl>
		</Pair>
	</StyleMap>
	<Placemark>
		<name>Untitled Polygon</name>
		<styleUrl>#m_ylw-pushpin</styleUrl>
		<Polygon>
			<tessellate>1</tessellate>
			<outerBoundaryIs>
				<LinearRing>
					<coordinates>
						152.2949846652809,-32.83771770022755,0 150.5011124700531,-33.94645586827908,0 151.4215042277178,-34.46817274472775,0 152.2949846652809,-32.83771770022755,0 
					</coordinates>
				</LinearRing>
			</outerBoundaryIs>
		</Polygon>
	</Placemark>
</Document>
</kml>

**Comment by yangli0516** [comment]
This is caused by the recent change of setting default DB schema in the .env file. It looks like the postgis is installed in the public schema, so setting the default schema to 'tlcmap'/'gazetter' breaks the postgis functions.

Have set the default schemas back to 'public' in the testing site. It should be working now.
