### ISSUE TITLE
Source URL and Linkback for Layer and Multilayer

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/TLCMap#14]
Layers currently only have 'Source URL' for linking to where the data came from - eg an online book, an online database, etc.
Users also need to be able to link back to their project website, and to ensure, when the data is distributed openly, it always goes around with that link to their project/their institute/their personal profile as creator/ or whatever the appropriate places is.
This is a high priority and should be a fairly easy database and interface change, though it does have spiralling repercussions. It involves:
For both Multilayer and Layer:
- add columns to the database tables
- add fields to the add and edit UI screens
- modify the KML, GeoJSON, CSV outputs
- maybe modify display of search results and any page there is a listing of layers and multilayers
- add it to map views
- check it hasn't broken search
- check it hasn't broken maps
(not sure if this would go under the current multilayer changes, or be a maintenance task)

**Comment by IanMcCrabb** [comment]
Figure this is outside the scope of the MultiLayers project so will leave this with Hugh to prioritize

**Comment by HughCraig** [comment]
This is important for preserving the chain of provenance and maintaining links to data owners' websites.

**Comment by yangli0516** [comment]
@BillPascoe Just to clarify, should the linkback URL displayed in the info block of map views under the description and warning? Should the URL be displayed as is, or the link text should be something meaningful?

**Comment by yangli0516** [comment]
It looks like the current KML, GeoJSON, and CSV export of layers only contain some basic metadata. Will skip these for the new linkback field until we make a decision in the future to include the full metadata in these export.

**Comment by BillPascoe** [comment]
If 'Linkback' has a URL in it, add a link in the view to a layers 'linkback'. For the moment have it at the bottom, next to 'help' and 'share'.
