### ISSUE TITLE
Code Review Refactor

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/TLCMap#15]
Results of a code review. Consider and do the refactor:

Hi Bill, 

Thank you for the invitation to review the Gazetteer service, I've gained access and am currently looking through the source code.

I'm unsure what format of code review would you be comfortable with so I'll just start with an email thread for the moment

From an initial look, I have a few queries/suggestions. I hope this would be helpful

Is there a specific requirement for this app to connect to 2 MySQL database instances and 2 PgSQL instances? According to config/database.php file, the default database connection would be pgsql, which applies for all the Model that doesn't have an explicit connection, whereas some Model have explicit connection attribute points to pgsql2. Is this intentional?

Also, most of the database migration in /database/migrations points to mysql2 as the connection to perform migration on. Is this still relevant?

Almost all of the routes in /routes/web.php are Route::any, it'll be a good idea to explicitly define Route::get and Route::post. This could leverage Laravel's own exception handler to throw 405 when an unknown request comes. This prevents people from executing DELETE or OPTIONS request on your resources

Speaking about Resources, I'm pretty sure the DatasetController can be a Resource Controller, so most of the boilerplate code can be generated via Laravel's own Resource mapping, something like Route::resource('dataset', 'DatasetController')

Currently most of the routes are defined in the routes/web.php file, but certain routes have specific middlewares, like auth and verified. It is best to define these in another file to reduce controller dependencies. This means there's no need to define authentication inside the controller, but define them on the route itself. This will make the Controller itself lighter and easier to test. Either bundle the auth and/or verified into the api routes at routes/api.php (this is defined in app/Providers/RouteServiceProvider.php) or use the middleware syntax like 

Route::middleware(['auth', 'verified'])->group(function () {
    Route::get('admin/users', 'Auth\AdminController@userManagement');
});

Mainly to improve readability and testing

Most of the business logic currently resides in the Controllers, I'd recommend abstract these Business Rule either into their respective Models or to a Domain class so that the business rule can be tested separately from the core flow

There's currently no tests written for the app, so I'm not sure how to test or the general functionality of the app. I understand that the default basic unit tests and basic feature test of Laravel relies on an instance of h2 database which is not ideal since a dependency on the system would be a PostgreSQL instance with the PostGIS extension and some seed data. Bitbucket does provide the pipeline functionality that would provide step by step provision of docker images for testing purpose. I think it'd be helpful if you can start looking at the Continuous Integration side of things. 

My apologies for the wall of text and some of these can come off as pedantic and not straight to the point. But based on my experience a lot of these can be overlooked and could potentially become a problem to deal with in the future.

Kind Regards,
Minh

**Comment by IanMcCrabb** [comment]
I think we can close this as it was considered in the refactor phase
