### ISSUE TITLE
Searches on names with spaces broken

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/TLCMap#31]
If you search for a word with a space in it the map viewer doesn't work. The console reports an error about json, however the json validator indicates it's ok. Trial and error make it pretty clear it's a problem with a space in the search term causing the problem. Could be something to do with character encoding the space then, maybe.
Examples, 'Red Hill' and 'New Bore': 
https://tlcmap.org/view/3d.html?load=https%3A%2F%2Ftlcmap.org%2Fghap%2Fsearch%3Fcontainsname%3Dnew%2Bbore%26searchausgaz%3Don%26searchpublicdatasets%3Don%26_token%3DfnGF0OVlXUTEKCbXjYCa9FV5doSTLI4wVAnswHhE%26leaflet-base-layers_41%3Don%26names%3D%26fuzzynames%3D%26containsnames%3D%26format%3Djson

https://tlcmap.org/view/3d.html?load=https%3A%2F%2Ftlcmap.org%2Fghap%2Fsearch%3Fcontainsname%3Dred%2Bhill%26searchausgaz%3Don%26searchpublicdatasets%3Don%26_token%3DfnGF0OVlXUTEKCbXjYCa9FV5doSTLI4wVAnswHhE%26leaflet-base-layers_41%3Don%26names%3D%26fuzzynames%3D%26containsnames%3D%26format%3Djson

**Comment by yangli0516** [comment]
It seems like that the space in the load URL is encoded as '+', which causes the loading problem from ArcGIS js. Changing it to '%20' solves the problem.

**Comment by yangli0516** [comment]
Have add the replacement in the frontend in 'show.blade.php' instead of changing it for the search URL.
