### ISSUE TITLE
Database configuration documentation

### ISSUE THREAD

**Issue by yangli0516** [HughCraig/TLCMap#5]
The configuration of database should be documented as I assume there would be two database connections: 'pgsql' and 'pgsql2'. The `.env.example` could be improved with example variables such as `DB_DATABASE_SECOND`.

**Comment by BillPascoe** [comment]
.env.example is probably way out of date. Any reference to mysql is legacy as it's been changed to postgres with postgis. I will send an updated one env file with passwords etc removed separately.
