### ISSUE TITLE
Some files are missing from the repository

### ISSUE THREAD

**Issue by yangli0516** [HughCraig/TLCMap#6]
The following is a list of missing files I encountered after the local installation from this repo:

/css/tlcmap.css
/js/tlcmapnav.js
/img/tlcmaplogo.jpg
/img/footmnt.png
/img/foottile.png
/te (Used for Temproal Earth view)

**Comment by BillPascoe** [comment]
Added these files to /public/tlcmap/
The are files from the main TLCMap website that are used for header, footer and navigation. You could set a link to them in the parent tlcmap on your local, if you have set up your local server to have the app under the folder  /ghap/ as it is on the live host.
