### ISSUE TITLE
Hide 'Collaborators' buttons and links.

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/TLCMap#88]
Remove 'My Collaborators' from the drop down under the profile menu, and also the 'Collaborator' button, until we have a proper way to do group admin of layers and multilayers.

**Comment by IanMcCrabb** [comment]
Presume we will do this as part of the GHAP Site UI changes

**Comment by BillPascoe** [comment]
There is one button left. If you log in and click on 'Account...' to view your profile, there is a button 'My Collaborators'.
![mycollaboratorsbutton](https://user-images.githubusercontent.com/27399676/188575429-e3c98fb6-8e7b-4338-ad1f-e22c43333ced.png)

**Comment by yangli0516** [comment]
Fixed.
