### ISSUE TITLE
Warning metadata colour

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/TLCMap#89]
In the multilayer metadata display box at top right, if there is a warning it should be displayed with a light alert background color, such as a pale yellow and subheading 'Warning'.

**Comment by IanMcCrabb** [comment]
Have assigned this to Hugh to confirm Priority with regards to maintenance budget

**Comment by BillPascoe** [comment]
The content warning in the Views metatdata box at top right should have a yellow background. Eg: the layer 'The Wreck Of The Ship "De Vergulde Draeck" On The Southland' seen in the view has a warning but it's not yellow. https://test.tlcmap.org/view/3d.html?load=https://test.tlcmap.org/ghap/publicdatasets/152/json

**Comment by yangli0516** [comment]
@BillPascoe , you probably need to force refresh the page (SHIFT + F5) to update the style sheets.

**Comment by BillPascoe** [comment]
Right yes. Should have known.
