### ISSUE TITLE
Advanced search options not working

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/TLCMap#94]
Maybe some, maybe all advanced search options not working.
Eg: if I select Format = geojson, it just gives me the normal UI output instead of JSON.
Check all Advanced Search options work. I think it has to do with their being two html form elements.
(this is in live, not introduced by recent changes)

**Comment by IanMcCrabb** [comment]
Have assigned this to Hugh to confirm Priority with regards to maintenance budget

**Comment by IanMcCrabb** [comment]
@BillPascoe can you perhaps identify what features aren't working

**Comment by yangli0516** [comment]
@BillPascoe I couldn't repro the issue on my dev environment. All advanced search parameters including the output format seem to work well. Could you let me know the exact parameters you used when you had the issue.

**Comment by BillPascoe** [comment]
The particular problem with selecting the output format is broken in prod but OK in test, so I'll close this job. However, I need to open 2 more high priority tasks with specific details about problems with advanced search.
