### ISSUE TITLE
Multilayer view help and share link

### ISSUE THREAD

**Issue by BillPascoe** [HughCraig/TLCMap#96]
In the multilayer metadata box at top right of views, 'Help' and 'Share' should go at the bottom, after the coloured dots.

**Comment by BillPascoe** [comment]
![HelpShareAtBottom](https://user-images.githubusercontent.com/27399676/188560665-c792a1a2-9435-499b-a3f1-83b47b7da25f.jpg)

**Comment by yangli0516** [comment]
@BillPascoe , the change was just been updated in the server. Please try again.
